[tool.poetry]
name = "lanarky"
version = "0.6.4"
description = "Ship production-ready LLM projects with FastAPI"
authors = ["Ajinkya Indulkar <26824103+ajndkr@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/ajndkr/lanarky"
repository = "https://github.com/ajndkr/lanarky"
license = "MIT"
packages = [{include = "lanarky"}]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = ">=0.95.2"
langchain = ">=0.0.175"
urllib3 = "<=1.26.15"  # added due to poetry errors
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.1"


[tool.poetry.group.docs.dependencies]
furo = "^2023.3.27"
sphinx-autobuild = "^2021.3.14"


[tool.poetry.group.tests.dependencies]
pytest = "^7.3.1"
pytest-cov = "^4.0.0"
pytest-asyncio = "^0.21.0"
coveralls = "^3.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
ignore = ["E501"]
